[FP-03] eCommerce - Sales Product Performance
shimoku-tech/shimoku-app-templates pull request #18
Opened 2023-12-28 14:01 UTC by HectorIdme

https://shimoku.atlassian.net/browse/SDT-116

2023-12-28 14:12 UTC, rotorrest requested changes

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/board.py
> +        dfs (DFs): An instance of a DFs class for handling data frames.
Please review the attributes, because board_name and dfs are not used to init the class

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/data/generate_sales_product_performance.py
> +    def random_date(start_date, end_date):
add types to this inputs

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/paths/overview.py
> +    def plot_header(self):
add doc string

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/paths/overview.py
> +    def plot_revenue_by_product(self):
add doc string

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/paths/overview.py
> +    def plot_online_vs_in_store_revenues(self):
add doc string

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/paths/overview.py
> +    def plot_incremental_sales_by_origin_campaign(self):
add doc string

2023-12-28 14:12 UTC, rotorrest commented on templates/sales_product_performance/paths/overview.py
add doc string

2023-12-28 14:13 UTC, rotorrest commented on templates/sales_product_performance/board.py
> +        dfs (DFs): An instance of a DFs class for handling data frames.
@rotorrest its done
https://github.com/shimoku-tech/shimoku-app-templates/commit/626dd2ea344e87d6010542afa2d4f92120fe8ec5

2023-12-28 17:10 UTC, HectorIdme commented on templates/sales_product_performance/board.py
> +        dfs (DFs): An instance of a DFs class for handling data frames.
The attributes in docstring were copied from saas_active_users_overview, but that template has the same problem. The template where the attributes are correctly is cross_selling.

2023-12-28 17:16 UTC, HectorIdme commented on templates/sales_product_performance/board.py
> +        dfs (DFs): An instance of a DFs class for handling data frames.
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-28 17:16 UTC, HectorIdme commented on templates/sales_product_performance/data/generate_sales_product_performance.py
> +    def random_date(start_date, end_date):
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-28 17:17 UTC, HectorIdme commented on templates/sales_product_performance/paths/overview.py
> +    def plot_header(self):
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-28 17:17 UTC, HectorIdme commented on templates/sales_product_performance/paths/overview.py
> +    def plot_revenue_by_product(self):
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-28 17:17 UTC, HectorIdme commented on templates/sales_product_performance/paths/overview.py
> +    def plot_online_vs_in_store_revenues(self):
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-28 17:17 UTC, HectorIdme commented on templates/sales_product_performance/paths/overview.py
> +    def plot_incremental_sales_by_origin_campaign(self):
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-28 17:17 UTC, HectorIdme commented on templates/sales_product_performance/paths/overview.py
@rotorrest it's done https://github.com/shimoku-tech/shimoku-app-templates/commit/ab091ddf76370afab780f3ac4af986d131aab23e

2023-12-29 11:50 UTC, rotorrest commented on templates/sales_product_performance/board.py
> +        dfs (DFs): An instance of a DFs class for handling data frames.
Thank you for the heads-up, I'm going to this in the other template.

2023-12-29 11:52 UTC, rotorrest approved these changes

2023-12-29 13:33 UTC, merged