[FP-06] eCommerce - Social Media Shares Performance
shimoku-tech/shimoku-app-templates pull request #27
Opened 2024-01-09 20:05 UTC by jkahnc

2024-01-09 20:20 UTC, HectorIdme reviewed
There are errors to fix.

2024-01-09 20:20 UTC, HectorIdme commented on templates/social_media_shares_performance/README.md
- There is no section in the README talking about data generation.
- You did not add the script (.py) to generate data in data folder.

2024-01-09 20:32 UTC, rotorrest requested changes

2024-01-09 20:32 UTC, rotorrest commented on templates/social_media_shares_performance/board.py
> +    """
this list of atributes is not correct

2024-01-09 20:32 UTC, rotorrest commented on templates/social_media_shares_performance/board.py
> +        import calendar
this is not the correct place to import a library

2024-01-09 20:32 UTC, rotorrest commented on templates/social_media_shares_performance/data/generate_social_media_shares.py
> +
extra space

2024-01-09 20:32 UTC, rotorrest commented on templates/social_media_shares_performance/requirements.txt
> +shimoku-api-python
Set a specific version of the shimoku lib

2024-01-09 21:05 UTC, jkahnc commented on templates/social_media_shares_performance/data/generate_social_media_shares.py
> +
solved 4fd9867b424b0778c3d36b6f94f16aae67250754

2024-01-09 21:05 UTC, jkahnc commented on templates/social_media_shares_performance/requirements.txt
> +shimoku-api-python
solved 4fd9867b424b0778c3d36b6f94f16aae67250754

2024-01-09 21:10 UTC, jkahnc commented on templates/social_media_shares_performance/board.py
> +    """
what do you mean by those are not the correct atributes about the class Board? Their are defined on the `__init__` function: https://github.com/shimoku-tech/shimoku-app-templates/pull/27/files#diff-673b0bbe3460cc24165d6cd0ab2dafabd72ba5de1a931db834a8094e0825623eR24-R33

2024-01-09 21:11 UTC, jkahnc commented on templates/social_media_shares_performance/board.py
> +        import calendar
I used the same convention that the template 
https://github.com/shimoku-tech/shimoku-app-templates/pull/27/files#diff-673b0bbe3460cc24165d6cd0ab2dafabd72ba5de1a931db834a8094e0825623eR124-R149

2024-01-10 15:59 UTC, rotorrest commented on templates/social_media_shares_performance/board.py
> +        import calendar
This convention is because it is necessary for the import of the classes that represent the paths, but it should not apply to regular libraries

2024-01-10 16:00 UTC, rotorrest commented on templates/social_media_shares_performance/board.py
> +    """
the only that is correct is `shimoku: Client` because is the only one in the __init__ function

    def __init__(self, shimoku: Client):

2024-01-10 20:50 UTC, jkahnc commented on templates/social_media_shares_performance/board.py
> +        import calendar
solved [61f4d06](https://github.com/shimoku-tech/shimoku-app-templates/pull/27/commits/61f4d069a79ab7dcb6ea0085a6370bfe735da784)

2024-01-10 20:51 UTC, jkahnc commented on templates/social_media_shares_performance/board.py
> +    """
As que talked, we let this part without modification?

2024-01-10 22:52 UTC, rotorrest approved these changes

2024-01-11 23:21 UTC, merged