[FP-09] Customer Satisfaction Performance
shimoku-tech/shimoku-app-templates pull request #28
Opened 2024-01-09 20:40 UTC by arturolinares24

@rotorrest @jkahnc Ready for review

2024-01-09 20:54 UTC, jkahnc reviewed
just an observation about the return in the plot functions on `paths/customer_satisfaction_performance.py`. It should be `return True`.  That's all

2024-01-09 21:09 UTC, HectorIdme requested changes
There are errors to fix.

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the header section of the dashboard.
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Key Performance Indicators (KPI) section of the dashboard.
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Customer Satisfaction section of the dashboard.
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        """
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Revenue Indicators section of the dashboard.
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Orders & Returned Orders section of the dashboard.
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        self.order += 1
Add return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Revenue Analysis section of the dashboard.
Add return to docstring

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/components.py
> +    """
Translate docstring to english.

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/components.py
> +    """
Add strcuture of docstring, parameters and return

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/utils.py
> +def get_data(file_names):
Add type for parameter file_names

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/utils.py
> +    Parameters:
Modify to standar use or Parameters or Args for all docstring, dont combine them.

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/utils.py
> +def process_sales_data(df):
Add type for parameter df

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/utils.py
> +def get_status(value):
Add type for parameter value

2024-01-09 21:09 UTC, HectorIdme commented on templates/customer_satisfaction_performance/utils/utils.py
> +def get_column_name_by_value(data_dict, value_to_find):
Add types for parametes data_dict and value_to_find

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the header section of the dashboard.
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Key Performance Indicators (KPI) section of the dashboard.
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Customer Satisfaction section of the dashboard.
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        """
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Revenue Indicators section of the dashboard.
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:57 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        Plot the Orders & Returned Orders section of the dashboard.
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        self.order += 1
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/utils/components.py
> +    """
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/utils/utils.py
> +    Parameters:
https://github.com/shimoku-tech/shimoku-app-templates/commit/3ce80e2a1474175120a69959817737223569620a Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/utils/utils.py
> +def process_sales_data(df):
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/utils/utils.py
> +def get_status(value):
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 14:58 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/utils/utils.py
> +def get_column_name_by_value(data_dict, value_to_find):
https://github.com/shimoku-tech/shimoku-app-templates/commit/dcf245413e61eeffcfd609bc742b7574046ed3ad. Changes made.

2024-01-10 15:02 UTC, rotorrest commented on templates/customer_satisfaction_performance/data/generate_customer_satisfaction_performance.py
> +def generate_data():
Be specific about the output type

2024-01-10 15:03 UTC, rotorrest commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +            color=orders_with_returns_status,
there is not a simgle comment in this section, improve this

2024-01-10 15:03 UTC, rotorrest commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
no comments

2024-01-10 15:04 UTC, rotorrest commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        return True
no coments here

2024-01-10 15:04 UTC, rotorrest commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
no comments here =(

2024-01-10 15:05 UTC, rotorrest commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        return True
no comments here =(

2024-01-10 15:07 UTC, rotorrest commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        self.order += 1
no comments here =(
its important to explain the pandas transformation

2024-01-10 15:42 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        self.order += 1
https://github.com/shimoku-tech/shimoku-app-templates/commit/63a27708da52f92b63a0c2a6815b95fce69b4d81 changes made. Deleted the dashboard link from README.md.

2024-01-10 15:42 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        return True
https://github.com/shimoku-tech/shimoku-app-templates/commit/63a27708da52f92b63a0c2a6815b95fce69b4d81 changes made. Deleted the dashboard link from README.md.

2024-01-10 15:42 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/63a27708da52f92b63a0c2a6815b95fce69b4d81 changes made. Deleted the dashboard link from README.md.

2024-01-10 15:42 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +        return True
https://github.com/shimoku-tech/shimoku-app-templates/commit/63a27708da52f92b63a0c2a6815b95fce69b4d81 changes made. Deleted the dashboard link from README.md.

2024-01-10 15:42 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +
https://github.com/shimoku-tech/shimoku-app-templates/commit/63a27708da52f92b63a0c2a6815b95fce69b4d81 changes made. Deleted the dashboard link from README.md.

2024-01-10 15:42 UTC, arturolinares24 commented on templates/customer_satisfaction_performance/paths/customer_satisfaction_performance.py
> +            color=orders_with_returns_status,
https://github.com/shimoku-tech/shimoku-app-templates/commit/63a27708da52f92b63a0c2a6815b95fce69b4d81 changes made. Deleted the dashboard link from README.md.

2024-01-10 15:47 UTC, HectorIdme approved these changes

2024-01-10 15:49 UTC, rotorrest approved these changes

2024-01-10 15:49 UTC, merged