[FP-10] Mobile App - Cohort Analysis
shimoku-tech/shimoku-app-templates pull request #32
Opened 2024-01-16 22:26 UTC by jkahnc

2024-01-17 12:53 UTC, arturolinares24 approved these changes
Approved. No comments.

2024-01-17 13:26 UTC, FelipeIdmeShimoku requested changes

2024-01-17 13:26 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/README.md
> +<!-- ![]() -->
The image of the dashboard is not uploaded.

2024-01-17 13:26 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/board.py
> +    Attributes:
What was the last conclusion with @rotorrest about this attributes, is correct to write them or you can avoid it and just take into account shimoku Client because is the unique parameter in the __init_ function?

2024-01-17 13:26 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/board.py
> +    def transform(self) -> bool:
I think that in escenarios like this, we need to try to create components to reduce code in transformation function, maybe trying to factorize long operations pandas like sum, and put it that components in the utils.py file.

2024-01-17 13:26 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/board.py
> +    def transform(self) -> bool:
I comment this thinking in the difficult to put all the function in the video.

2024-01-17 13:31 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/board.py
> +    Attributes:
the attributes represent the class attributes.

2024-01-17 13:31 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/README.md
> +<!-- ![]() -->
it will be updated after get the workspaces

2024-01-17 14:00 UTC, rotorrest requested changes

2024-01-18 21:58 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/board.py
> +    def transform(self) -> bool:
I have been working in refactor the code and create components. In the case of the Age section, It works with range and it is easier just let the code like that.

In any case to response to your last comment, we focus on the path folder, we don't show the transform function on the video.

[9213047](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/9213047fae0974a04b221ed325fdae74b0a3b4c7)

2024-01-18 21:58 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/paths/cohort_analysis.py
> +        Parameters:
solved [164eee1](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/164eee15652a4d59ef878c7a39d20939d75b1955)

2024-01-18 21:59 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/board.py
> +        UO.plot()
solved [164eee1](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/164eee15652a4d59ef878c7a39d20939d75b1955)

2024-01-18 22:01 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/README.md
> +<!-- ![]() -->
As we still don't have the workspace and Albert has given me the OK with the data generation, I update the screenshot 

solved [0b2130a](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/0b2130a9b28940035b97cf3bea1abe32d7b20ab9)

2024-01-19 14:04 UTC, rotorrest approved these changes

2024-01-19 14:55 UTC, FelipeIdmeShimoku approved these changes

2024-01-19 14:55 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +) -> list:
Add docstring for this function

2024-01-19 14:55 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +
Add docstring for this function

2024-01-19 14:55 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +) -> list:
Add docstring for this function

2024-01-19 14:55 UTC, FelipeIdmeShimoku commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +    filter_date = df_users["register_date"].between(
Add docstring for this function

2024-01-19 18:58 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +    filter_date = df_users["register_date"].between(
solved [dfb7604](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/dfb7604ebda94cdc9deed64bd3cbd93a0b4696b0)

2024-01-19 18:59 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +) -> list:
solved [dfb7604](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/dfb7604ebda94cdc9deed64bd3cbd93a0b4696b0)

2024-01-19 18:59 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +
solved [dfb7604](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/dfb7604ebda94cdc9deed64bd3cbd93a0b4696b0)

2024-01-19 18:59 UTC, jkahnc commented on templates/mobile_app_cohort_analysis/utils/utils.py
> +) -> list:
solved [dfb7604](https://github.com/shimoku-tech/shimoku-app-templates/pull/32/commits/dfb7604ebda94cdc9deed64bd3cbd93a0b4696b0)

2024-01-19 19:01 UTC, merged